### ISSUE TITLE
Doesn't seems to work

### ISSUE THREAD

**Issue by jingjinghack** [dude719/SigMaker-x64#1]
It just gave me a wrong sig.
![tim 20171219174317](https://user-images.githubusercontent.com/16219523/34153414-ed47827e-e4ec-11e7-904b-b51f0ed481a5.png)

**Comment by dude719** [comment]
This is not a bug. It does an intelligent scan for the smallest signature. If you look up that signature, it's probably a reference to the function you're trying to sig. (Notice the (+0x1) there too).

**Comment by jingjinghack** [comment]
Sorry, it's my wrong.
