### ISSUE TITLE
Infinity loop in function AutoGenerate( ea_t dwAddress, qSigVector& refvecSig )

### ISSUE THREAD

**Issue by bananasss00** [dude719/SigMaker-x64#15]
**loop here:**
do
{
....
//for some reason vecSig.size() can be 0 then HasOneHitSig all time return false -> infinity loop
} while (HasOneHitSig( vecSig ) == false);

**for example:**
in current csgo release 11.07.2018 client.dll.
search sig for address .text:1046E3A6

**mb this fix?**
if (nTotalCount < 1 _**|| vecSig.size() < 1**_) // vecSig.size()
        {
            hide_wait_box( );

            if (Settings.iLogLevel >= 2)
            {
                msg( "automated signature generation failed. Unable to proceed.\n" );
            }

            return false;
        }

**Comment by gir489** [comment]
Upload the DLL so can we test against it.

**Comment by gir489** [comment]
With whatever the latest build was, I was able to call Auto create ida pattern with no problems or crashes.

```
adding references
sig: E8 ? ? ? ? 68 ? ? ? ? B9 ? ? ? ? E8 ? ? ? ? 8B 4B 04 
adding references
sig: E8 ? ? ? ? 68 ? ? ? ? B9 ? ? ? ? E8 ? ? ? ? 8B 4B 04 
```

![image](https://user-images.githubusercontent.com/7742541/42667179-aa588a40-8617-11e8-8a58-f0912e61b748.png)

Closing as not reproducible.

**Comment by bananasss00** [comment]
sorry for reopen. problem not solved
