### ISSUE TITLE
Can not compile 32-bit variant.

### ISSUE THREAD

**Issue by gir489** [dude719/SigMaker-x64#5]
It seems the configuration committed with the project for Win32 is the same for the original SigMaker.

I tried copying Release64's x64 over to Release64's Win32 configuration, keeping everything the same except for Target Machine, Preprocessor Definitions, output file name, and additional library directories. But I still get the error:

`LoadLibrary(D:\Program Files\IDA 7.0\plugins\sigmaker.dll) error: %1 is not a valid Win32 application.
D:\Program Files\IDA 7.0\plugins\sigmaker.dll: can't load file`

**Comment by dude719** [comment]
IDA 7 only reads 64 bit PE plugin files, and does not support 32 bit, so this is a non issue. I don't even think the IDA 7 SDK allows you to compile for 32 bit without a load of errors.

**Comment by gir489** [comment]
> IDA 7 only reads 64 bit PE plugin files, and does not support 32 bit, so this is a non issue. I don't even think the IDA 7 SDK allows you to compile for 32 bit without a load of errors.
That is correct. But the existence of the x86 build confused me at first. After reading the 7.0 SDK notes, it became obvious why you had a Release and Release64 build. I've addressed this in a pull request.

**Comment by dude719** [comment]
I just saw, thanks!
