### ISSUE TITLE
IDA 7

### ISSUE THREAD

**Issue by richard-adlava** [dude719/SigMaker-x64#8]
Does not work for IDA 7
LoadLibrary(C:\Program Files\IDA Freeware 7.0\plugins\sigmaker64.dll) error: The specified procedure could not be found.
C:\Program Files\IDA Freeware 7.0\plugins\sigmaker64.dll: can't load file

**Comment by dude719** [comment]
This is because you're using the freeware version of IDA v7.0. The freeware version doesn't fully support plugins, so you'll need to upgrade to IDA Pro v7.0.
