### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by stanriders** [dude719/SigMaker-x64#9]
It's been a while

**Comment by dude719** [comment]
Why would you open an issue for this? I haven't made a new release because no changes have been made. If you want a new release, make some contributions!

**Comment by stanriders** [comment]
Ah, my bad, thought that last release is older than it actually is. I just needed ELF support and I don't have SDK installed.
Sorry ¯\_(ツ)_/¯

**Comment by dude719** [comment]
I would distribute the SDK if it were allowed to do so. Apparently the cracked version of IDA Pro 7 doesnt come with the complete SDK (according to multiple sources). I'll build a new release when I get the time, I just haven't been on my tool development machine in a while.

**Comment by stanriders** [comment]
Thank you!

**Comment by dude719** [comment]
New release was just made thanks to [gir489](https://github.com/gir489): https://github.com/dude719/SigMaker-x64/releases/tag/1.0.2
